import type { NextPage } from "next";
import Head from "next/head";
import Link from "next/link";
import styles from "../../styles/Home.module.css";


const BlogHome: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <h1 className={styles.title}> Blog Home Page</h1>
        <ul>
          <li> <Link href="/blog/2022-20-07/cherry-blossom">Blog 1</Link></li>
          <li> <Link href="/blog/2022-13-02/birthday">Blog 2</Link></li>
          <li> <Link href={{
            pathname: "/blog/[date]/[slug]",
            query: {
                date:"2022-01-01",
                slug:"happynewyear"
            }
          }}>Blog 3</Link></li>


        </ul>
      </main>
    </div>
  );
};
export default BlogHome;